apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pacman-api
  description: API REST de pacman
spec:
  type: openapi
  lifecycle: production
  owner: team-arcade
  definition:
    $text: ./../apis-specs/pacman/openapi.yaml
